/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/*import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;*/

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import dbconnection.DBconnect;


/**
 *
 * @author Maneesha
 */
public class SalaryForm extends javax.swing.JFrame {
    
    DBconnect con = new DBconnect();
    PreparedStatement  pst = null;
    Statement stmt = null;
    ResultSet rs = null;
    DefaultTableModel model = null;
    Connection conn = null;
    

    /**
     * Creates new form SalaryForm
     */
    public SalaryForm() {
        initComponents();
       
     conn = DBconnect.connect();
       
     Object col[]={"empId","month","year","bonus","overtime","netSalary"};
     
     
    }
    public void tablelod(){
        
        try {
            String sql="Select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.overTime from attendance a,employee e";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        basicsalarybox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        overtimebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        basicsalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bonusbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        epfbox = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        viewslip = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstnamebox = new javax.swing.JTextField();
        monthbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastnamebox = new javax.swing.JTextField();
        idbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        netsalarybox = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ratebox = new javax.swing.JTextField();
        cal = new javax.swing.JButton();
        etfbox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        totalovertimebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel2.setText("Basic Salary");

        basicsalarybox.setEditable(false);
        basicsalarybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Over Time Hours");

        overtimebox.setEditable(false);
        overtimebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Bonus");

        basicsalary.setEditable(false);
        basicsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryActionPerformed(evt);
            }
        });
        basicsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                basicsalaryKeyPressed(evt);
            }
        });

        jLabel5.setText("ETF");

        jLabel6.setText("ETF");

        epfbox.setEditable(false);
        epfbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epfboxActionPerformed(evt);
            }
        });

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        viewslip.setText("VIEW SLIP");
        viewslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewslipActionPerformed(evt);
            }
        });

        jLabel9.setText("First Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("             SALARY MANAGEMENT");

        firstnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameboxActionPerformed(evt);
            }
        });

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "Auguest", "September", "October", "November", "December", " " }));
        monthbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthboxActionPerformed(evt);
            }
        });

        jLabel11.setText("Month");

        jLabel12.setText("Last Name");

        jLabel1.setText("ID");

        lastnamebox.setEditable(false);

        idbox.setEditable(false);

        jLabel14.setText("Year");

        label1.setText("Net Salary");

        netsalarybox.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FirstName", "LastName", "ID", "BasicSalary", "EPF", "ETF", "OverTime"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Total over Time");

        jTextField1.setEditable(false);

        jLabel8.setText("RatePerHour :");

        ratebox.setEditable(false);
        ratebox.setText("250.00");
        ratebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateboxActionPerformed(evt);
            }
        });

        cal.setText("CAL");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        etfbox.setEditable(false);

        jLabel15.setText("Total Over Time");

        totalovertimebox.setEditable(false);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(firstnamebox, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(basicsalarybox)
                                        .addComponent(basicsalary)
                                        .addComponent(bonusbox)
                                        .addComponent(epfbox)
                                        .addComponent(etfbox)
                                        .addComponent(overtimebox)
                                        .addComponent(totalovertimebox)))))
                        .addGap(7, 7, 7)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(841, 841, 841)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addComponent(search)
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addComponent(ratebox, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cal)
                                        .addGap(320, 320, 320)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(viewslip, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(netsalarybox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameLayout.createSequentialGroup()
                        .addComponent(search)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(bonusbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(epfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(etfbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ratebox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cal)
                                                .addComponent(jLabel8))
                                            .addGroup(nameLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(overtimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalovertimebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(addbtn))
                                    .addGroup(nameLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deletebtn)
                                .addGap(18, 18, 18)
                                .addComponent(updatebtn)
                                .addGap(18, 18, 18)
                                .addComponent(viewslip)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(nameLayout.createSequentialGroup()
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(firstnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(netsalarybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                                .addComponent(basicsalarybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nameLayout.createSequentialGroup()
                                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void basicsalaryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalaryboxActionPerformed

    private void basicsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalaryActionPerformed

    private void viewslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewslipActionPerformed
      
        SalarySlip s1 = new SalarySlip(); 
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewslipActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
   
    
   String name = firstnamebox.getText();
   String searchQuery = "select e.fName,e.lName,e.empId,e.basicSalary,e.EPF,e.ETF,a.overTime from employee e,"
           + " attendance a where fName LIKE '%"+name+"%'";
    PreparedStatement ps;
    ResultSet rs;
        
        
        try{
            
            ps = (PreparedStatement) con.connect().prepareStatement(searchQuery);
            rs = ps.executeQuery(searchQuery);
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch (SQLException e){
            Logger.getLogger(SalaryForm.class.getName()).log(Level.SEVERE,null,e);
            
        }
        
    
   
    
    
    
    }//GEN-LAST:event_searchActionPerformed

    private void firstnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameboxActionPerformed

    private void monthboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthboxActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       
        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();
        String bonus = bonusbox.getText();
        String overTime = totalovertimebox.getText();
        String netSalary = netsalarybox.getText();
        
         PreparedStatement ps;
     
        try{
        String sql = "INSERT INTO salary (empId, month, year, bonus, overtime, netSalary) "+ "VALUES (?,?,?,?,?,?)";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql);
        preparedStatement.setInt(1, Integer.parseInt(empId));
        preparedStatement.setString(2, month);
        preparedStatement.setString(3, year); 
        preparedStatement.setDouble(4, Double.parseDouble(bonus));
        preparedStatement.setDouble(5, Double.parseDouble(overTime));
        preparedStatement.setDouble(6, Double.parseDouble(netSalary));
        preparedStatement.executeUpdate(); 
        
        } catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"inserted successfully");  
      
    
     
    try{
         String sql= "insert into salary (empId,month,year,overtime,netSalary)";
         
     } catch(Exception e){}
         
     
     
        
       
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       
//        Update u1 = new Update();
//        u1.setVisible(true);
//        this.dispose();
        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();
        String bonus = bonusbox.getText();
        String overTime = totalovertimebox.getText();
        String netSalary = netsalarybox.getText();
        
         PreparedStatement ps;
     
        try{
        String sql = "UPDATE salary set bonus = ?, overtime= ?, netSalary= ? WHERE empId = ? AND  month =? AND year=?";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql); 
        preparedStatement.setDouble(1, Double.parseDouble(bonus));
        preparedStatement.setDouble(2, Double.parseDouble(overTime));
        preparedStatement.setDouble(3, Double.parseDouble(netSalary));
        preparedStatement.setInt(4, Integer.parseInt(empId));
        preparedStatement.setString(5, month);
        preparedStatement.setString(6, year);
        preparedStatement.executeUpdate(); 
        
        } catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"inserted successfully");  
      
    
     
    try{
//         String sql= "insert into salary (empId,month,year,overtime,netSalary)";
         
     } catch(Exception e){}
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String empId = idbox.getText();
        String month = monthbox.getSelectedItem().toString();
        String year = jComboBox2.getSelectedItem().toString();
//        String bonus = bonusbox.getText();
//        String overTime = totalovertimebox.getText();
//        String netSalary = netsalarybox.getText();

        
         PreparedStatement ps;
     
        try{
        String sql = "DELETE FROM salary WHERE empId = ? AND  month =? AND year=?";
        
        PreparedStatement preparedStatement = con.connect().prepareStatement(sql); 
        preparedStatement.setInt(1, Integer.parseInt(empId));
        preparedStatement.setString(2, month);
        preparedStatement.setString(3, year);
        preparedStatement.executeUpdate(); 
        
        
        tablelod();
        }
        
        catch (SQLException e){
        
        }
               
           JOptionPane.showMessageDialog(null,"Deleted successfully");  
      
    
     
    try{
//         String sql= "insert into salary (empId,month,year,overtime,netSalary)";
         
     } catch(Exception e){}
    
    }//GEN-LAST:event_deletebtnActionPerformed

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
      DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int selectedRowIndex = jTable1.getSelectedRow();
       
     
        firstnamebox.setText(model.getValueAt(selectedRowIndex,0).toString());
        idbox.setText(model.getValueAt(selectedRowIndex,2).toString());
        lastnamebox.setText(model.getValueAt(selectedRowIndex,1).toString());
        basicsalary.setText(model.getValueAt(selectedRowIndex,3).toString());
        epfbox.setText(model.getValueAt(selectedRowIndex,4).toString());
        etfbox.setText(model.getValueAt(selectedRowIndex,5).toString());
        overtimebox.setText(model.getValueAt(selectedRowIndex,6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
      
        final double Rate = 250.00;
        double overTime;
        double totalOverTime;
        
        overTime = Double.parseDouble(overtimebox.getText());
        
        totalOverTime = overTime * Rate;
        totalovertimebox.setText(Double.toString(totalOverTime));
        
                
    }//GEN-LAST:event_calActionPerformed

    private void epfboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epfboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epfboxActionPerformed

    private void overtimeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overtimeboxActionPerformed

    private void rateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateboxActionPerformed

    private void basicsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basicsalaryKeyPressed
        
    }//GEN-LAST:event_basicsalaryKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double basicSalary;
        double EPF;
        double ETF;
        double bonus;
        double totalOverTime;
        double netSalary;
        
      basicSalary  = Double.parseDouble(basicsalary.getText());
      EPF  = Double.parseDouble(epfbox.getText());
      ETF  = Double.parseDouble(etfbox.getText());
      bonus = Double.parseDouble(bonusbox.getText());
      totalOverTime  = Double.parseDouble(totalovertimebox.getText());
      
      netSalary =( basicSalary + bonus + totalOverTime) -(EPF + ETF);
      netsalarybox.setText(Double.toString(netSalary));
      
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

      
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryForm().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField basicsalary;
    private javax.swing.JTextField basicsalarybox;
    private javax.swing.JTextField bonusbox;
    private javax.swing.JButton cal;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField epfbox;
    private javax.swing.JTextField etfbox;
    private javax.swing.JTextField firstnamebox;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private javax.swing.JTextField lastnamebox;
    private javax.swing.JComboBox<String> monthbox;
    private javax.swing.JPanel name;
    private java.awt.TextField netsalarybox;
    private javax.swing.JTextField overtimebox;
    private javax.swing.JTextField ratebox;
    private javax.swing.JButton search;
    private javax.swing.JTextField totalovertimebox;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewslip;
    // End of variables declaration//GEN-END:variables
}
